[phases.setup]
nixPkgs = ["nodejs_20", "python3", "python3Packages.requests", "python3Packages.pip"]

[phases.install]
cmds = ["cd client && npm install --legacy-peer-deps"]

[start]
cmd = "node client/server.js"
