[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
onchain = "BhdRJ6avmPLhEhbUmhNh7DMyrTHtDtce4VM9xjQFgK1k"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
